#!/bin/bash
set -e

# Requirements (Fedora)
# sudo dnf install python3-libselinux

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"

"$ROOT/scripts/build-wrapper-python"
. "$ROOT/dist/python-env/bin/activate"

pip install \
	ansible==3.0.0
