#!/bin/bash
set -e

# Requirements (Fedora)
# sudo dnf install python3-libselinux
# And make sure to create the virtualenv with --system-site-packages!

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"

"$ROOT/scripts/build-wrapper-python"

. "$ROOT/dist/python-env/bin/activate"
pip install \
	ansible==3.0.0 \
	os-client-config==2.1.0 \
	rackspaceauth==0.8.1
