#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")

function c () {
	curl "localhost:8080/$1" \
		--silent \
		--request POST \
		"${@:2}" | python -m json.tool
}

mkdir --parents "$HERE/data/"

puccini-tosca compile "$HERE/../tosca/requirements-and-capabilities.yaml" | \
puccini-clout scriptlet exec "$HERE/dgraph.js" \
	> "$HERE/data/tosca.json"

c alter --data '{"drop_all": true}'

c mutate --data-binary @"$HERE/data/tosca.json" \
	--header 'X-Dgraph-MutationType: json' \
	--header 'X-Dgraph-CommitNow: true'
