#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

git_version

function build () {
	local TOOL=$1
	pushd "$ROOT/$TOOL" > /dev/null
	go install \
		-ldflags " \
			-X '$MODULE/version.GitVersion=$VERSION' \
			-X '$MODULE/version.GitRevision=$REVISION' \
			-X '$MODULE/version.Timestamp=$TIMESTAMP'"
	popd > /dev/null
	echo "built $GOPATH/bin/$TOOL"
}

build puccini-tosca
build puccini-clout

cp "$ROOT/puccini-csar" "$GOPATH/bin/"
