#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

GOOS=${GOOS:-js} # try wasip1

git_version

mkdir --parents "$ROOT/dist"

function build () {
	local TOOL=$1
	local WASM=$ROOT/dist/$TOOL.wasm
	pushd "$ROOT/$TOOL" > /dev/null
	GOOS="$GOOS" GOARCH=wasm go build \
		-o "$WASM" \
		-ldflags " \
			-X 'github.com/tliron/kutil/version.GitVersion=$VERSION' \
			-X 'github.com/tliron/kutil/version.GitRevision=$REVISION' \
			-X 'github.com/tliron/kutil/version.Timestamp=$TIMESTAMP'"
	popd > /dev/null
	m "built $WASM"
}

build puccini-tosca
build puccini-clout
build puccini-csar
