#!/bin/bash
set -e

# Requirements (Fedora)
# sudo dnf install python3-libselinux

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

SUFFIX=$SUFFIX "$HERE/build-wrapper-python" -i
. "$ROOT/dist/python-env/bin/activate"

pip install ansible==3.1.0

ansible-galaxy collection build \
	"$ROOT/wrappers/ansible/ansible_collections/puccini/tosca" \
	--output-path "$ROOT/dist/ansible-galaxy" \
	--force
