#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

git_version

# Requirements (Fedora)
# sudo dnf install python3-virtualenv

# virtualenv
python3 -m venv --system-site-packages "$ROOT/dist/python-env"
. "$ROOT/dist/python-env/bin/activate"
pip install --upgrade pip

PUCCINI_REPO=$ROOT PUCCINI_VERSION=$VERSION PUCCINI_GO_VERSION=$GO_VERSION \
pip install "$ROOT/wrappers/python"
