#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build-library"

cp "$ROOT/dist/libpuccini.so" "$ROOT/wrappers/ruby/lib/"

git_version

PUCCINI_VERSION=${VERSION:1} \
gem build \
	-C "$ROOT/wrappers/ruby" \
	--output ../../dist/puccini.gem \
	"$ROOT/wrappers/ruby/puccini.gemspec"
