#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

git_version

function build () {
	local TOOL=$1
	#pushd "$ROOT/$TOOL" > /dev/null
#	podman run --rm --volume="$ROOT:/src" --security-opt=label=disable tinygo ls /src
	podman run --rm --volume="$ROOT:/src" --volume="$GOPATH:/go" --env=GOPATH=/go --security-opt=label=disable tinygo tinygo build -o /src/$TOOL.wasm -target wasm "$TOOL"
#		-ldflags " \
#			-X 'github.com/tliron/kutil/version.GitVersion=$VERSION' \
#			-X 'github.com/tliron/kutil/version.GitRevision=$REVISION' \
#			-X 'github.com/tliron/kutil/version.Timestamp=$TIMESTAMP'"
	#popd > /dev/null
	m "built $GOPATH/bin/$TOOL"
}

build puccini-tosca
build puccini-clout

rsync "$ROOT/puccini-csar" "$GOPATH/bin/"
