#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$BASH_SOURCE")")
. "$HERE/_env"

git_version

mkdir --parents "$ROOT/dist"

function build () {
	local TOOL=$1
	local WASM=$ROOT/dist/$TOOL.wasm
	pushd "$ROOT/$TOOL" > /dev/null
	GOOS=js GOARCH=wasm go build \
		-o "$WASM" \
		-ldflags " \
			-X '$MODULE/version.GitVersion=$VERSION' \
			-X '$MODULE/version.GitRevision=$REVISION' \
			-X '$MODULE/version.Timestamp=$TIMESTAMP'"
	popd > /dev/null
	echo "built $WASM"
}

build puccini-tosca
