#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

mkdir --parents "$ROOT/dist"

ENTRY_DEFINITIONS=main.yaml \
OTHER_DEFINITIONS='"other 1.yaml" other\ 2.yaml' \
"$ROOT/puccini-csar" "$ROOT/dist/cloud.csar" "$ROOT/examples/csar"
