#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

mkdir --parents "$ROOT/dist"

ENTRY_DEFINITIONS=hello-world.yaml \
"$ROOT/puccini-csar" "$ROOT/dist/openstack.csar" "$ROOT/examples/openstack"
