#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

git_version

function build () {
	local TOOL=$1
	pushd "$ROOT/executables/$TOOL" > /dev/null
	tinygo build \
		-o "$ROOT/dist/$TOOL" \
		-ldflags " \
			-X 'github.com/tliron/kutil/version.GitVersion=$VERSION' \
			-X 'github.com/tliron/kutil/version.GitRevision=$REVISION' \
			-X 'github.com/tliron/kutil/version.Timestamp=$TIMESTAMP'"
	popd > /dev/null
	m "built $GOPATH/bin/$TOOL"
}

build puccini-tosca
build puccini-clout
build puccini-csar

rsync "$ROOT/puccini-csar" "$GOPATH/bin/"
