#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$BASH_SOURCE")")
. "$HERE/_env"

git_version

# virtualenv
python -m venv "$ROOT/dist/python-env"
. "$ROOT/dist/python-env/bin/activate"
pip install --upgrade pip

PUCCINI_REPO=$ROOT PUCCINI_VERSION=$VERSION \
pip install "$ROOT/wrappers/python"
