#!/bin/bash
set -e

if [ "$NOBUILD" == true ]; then
	exit
fi

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

git_version

function build () {
	local TOOL=$1
	pushd "$ROOT/$TOOL" > /dev/null
	CGO_ENABLED=0 go install \
		-ldflags " \
			-X 'github.com/tliron/kutil/version.GitVersion=$VERSION' \
			-X 'github.com/tliron/kutil/version.GitRevision=$REVISION' \
			-X 'github.com/tliron/kutil/version.Timestamp=$TIMESTAMP'"
	popd > /dev/null
	m "built ${GOPATH//\\/\\\\}/bin/$TOOL"
}

build puccini-tosca
build puccini-clout
build puccini-csar
