#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

gofmt -w -s -e \
	"$ROOT/ard" \
	"$ROOT/clout" \
	"$ROOT/clout/js" \
	"$ROOT/common" \
	"$ROOT/common/format" \
	"$ROOT/common/problems" \
	"$ROOT/common/reflection" \
	"$ROOT/common/terminal" \
	"$ROOT/puccini-js" \
	"$ROOT/puccini-js/commands" \
	"$ROOT/puccini-tosca" \
	"$ROOT/puccini-tosca/commands" \
	"$ROOT/tosca" \
	"$ROOT/tosca/compiler" \
	"$ROOT/tosca/csar" \
	"$ROOT/tosca/grammars" \
	"$ROOT/tosca/grammars/cloudify_v1_3" \
	"$ROOT/tosca/grammars/hot" \
	"$ROOT/tosca/grammars/tosca_v1_0" \
	"$ROOT/tosca/grammars/tosca_v1_1" \
	"$ROOT/tosca/grammars/tosca_v1_2" \
	"$ROOT/tosca/grammars/tosca_v1_3" \
	"$ROOT/tosca/normal" \
	"$ROOT/tosca/parser" \
	"$ROOT/tosca/profiles" \
	"$ROOT/tosca/profiles/bpmn/v1_0" \
	"$ROOT/tosca/profiles/cloudify/v5_0_5" \
	"$ROOT/tosca/profiles/common/v1_0" \
	"$ROOT/tosca/profiles/hot/v1_0" \
	"$ROOT/tosca/profiles/kubernetes/v1_0" \
	"$ROOT/tosca/profiles/openstack/v1_0" \
	"$ROOT/tosca/profiles/simple/v1_0" \
	"$ROOT/tosca/profiles/simple/v1_1" \
	"$ROOT/tosca/profiles/simple/v1_2" \
	"$ROOT/tosca/profiles/simple/v1_3" \
	"$ROOT/tosca/profiles/simple-for-nfv/v1_0" \
	"$ROOT/url" \
	"$ROOT/version"
