#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

EXECUTABLES=$ROOT/executables

rm --force "$EXECUTABLES/puccini-tosca"/*.pgo
rm --force "$EXECUTABLES/puccini-clout"/*.pgo
rm --force "$EXECUTABLES/puccini-csar"/*.pgo
rm --force "$ROOT/library"/*.pgo

"$HERE/build"

if [ "$1" == -c ]; then
	exit
fi

m "creating $EXECUTABLES/puccini-csar/default.pgo"

mkdir --parents "$ROOT/dist"

puccini-csar create "$ROOT/dist/cloud.tar.gz" "$ROOT/examples/csar" \
    --entry-definitions=main.yaml \
    --other-definitions='other 1.yaml' \
    --other-definitions='other 2.yaml' \
	--cpu-profile="$EXECUTABLES/puccini-csar/default1.pgo" > /dev/null 2>&1

puccini-csar create "$ROOT/dist/cloud.csar" "$ROOT/examples/csar" \
    --entry-definitions=main.yaml \
    --other-definitions='other 1.yaml' \
    --other-definitions='other 2.yaml' \
	--cpu-profile="$EXECUTABLES/puccini-csar/default2.pgo" > /dev/null 2>&1

go tool pprof -proto "$EXECUTABLES/puccini-csar/default1.pgo" "$EXECUTABLES/puccini-csar/default2.pgo" > "$EXECUTABLES/puccini-csar/default.pgo"
rm "$EXECUTABLES/puccini-csar/default1.pgo" "$EXECUTABLES/puccini-csar/default2.pgo"

m "creating $EXECUTABLES/puccini-tosca/default.pgo"

. "$HERE/_start-http-server"

puccini-tosca compile "http://localhost:8000/cloud.tar.gz" --coerce \
	--cpu-profile="$EXECUTABLES/puccini-tosca/default1.pgo" > /dev/null 2>&1

puccini-tosca compile "http://localhost:8000/cloud.csar" --coerce \
	--cpu-profile="$EXECUTABLES/puccini-tosca/default2.pgo" > /dev/null 2>&1

go tool pprof -proto "$EXECUTABLES/puccini-tosca/default1.pgo" "$EXECUTABLES/puccini-tosca/default2.pgo" > "$EXECUTABLES/puccini-tosca/default.pgo"
rm "$EXECUTABLES/puccini-tosca/default1.pgo" "$EXECUTABLES/puccini-tosca/default2.pgo"

cp "$EXECUTABLES/puccini-tosca/default.pgo" "$ROOT/library/default.pgo"

m "creating $EXECUTABLES/puccini-clout/default.pgo"

puccini-tosca compile "http://localhost:8000/cloud.tar.gz" | \
puccini-clout scriptlet exec tosca.resolve \
	--cpu-profile="$EXECUTABLES/puccini-clout/default.pgo" > /dev/null 2>&1

"$HERE/build"
