#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

git_version

VERSION=${SHORT_VERSION:1}$SUFFIX
PYTHON_VERSION=cp39
PLATFORM=manylinux1_x86_64 #linux_x86_64

SDIST=dist/puccini-$VERSION.tar.gz
BDIST=dist/puccini-$VERSION-$PYTHON_VERSION-$PYTHON_VERSION-$PLATFORM.whl

cd "$ROOT/wrappers/python"

rm --force --recursive env
python3 -m venv env
. env/bin/activate
pip install --upgrade pip
pip install wheel twine

echo "$VERSION" > "$ROOT/wrappers/python/VERSION"

PUCCINI_REPO=$ROOT PUCCINI_GO_VERSION=$GO_VERSION \
./setup.py sdist bdist_wheel --plat-name=$PLATFORM

#auditwheel repair "$BDIST"

if [ "$1" == -u ]; then
    gpg --detach-sign --armor --yes "$SDIST"
    gpg --detach-sign --armor --yes "$BDIST"

    # Upload to PyPI
    twine upload \
        "$SDIST" \
        "$SDIST.asc" \
        "$BDIST" \
        "$BDIST.asc"
fi
