#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$BASH_SOURCE")")
. "$HERE/_env"

rm --force "$ROOT/go.mod" "$ROOT/go.sum"

cd "$ROOT"
go mod init github.com/tliron/puccini

"$HERE/test"

go mod tidy
