#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

go get -u github.com/goreleaser/goreleaser

# Uses the current tag for the release version
# (So you likely want to tag before running this)

WORK=$(mktemp --directory)

function the_end () {
	local ERR=$?
	rm --recursive --force "$WORK"
	exit $ERR
}

trap the_end EXIT

# Create a clean copy of our repo
rsync --recursive "$ROOT/" "$WORK"
cd "$WORK"
git clean -xdf
find . -type f -name .gitignore -exec rm {} \;

if [ "$1" == -t ]; then
	goreleaser --parallelism=$(nproc) --skip-validate --snapshot --skip-publish
else
	goreleaser --parallelism=$(nproc) --skip-validate
fi

# Copy releases back here
rm --recursive --force "$ROOT/dist/release"
rsync --recursive "$WORK/dist/" "$ROOT/dist/release"
