#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

go get -u github.com/goreleaser/goreleaser

# Uses the current tag for the release version
# (So you likely want to tag before running this)

# Useful flags:
# --snapshot - doesn't need a tag
# --skip-publish - don't publish, just build

WORK=$(mktemp --directory)

function the_end () {
	local ERR=$?
	rm --recursive --force "$WORK"
	exit $ERR
}

trap the_end EXIT

rsync --recursive "$ROOT/" "$WORK"
cd "$WORK"
git clean -xdf
find . -type f -name .gitignore -exec rm {} \;
goreleaser --parallelism=$(nproc) --skip-validate "$@"
rm --recursive --force "$ROOT/dist/release"
rsync --recursive "$WORK/dist/" "$ROOT/dist/release"
