#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build-csar"

. "$HERE/_start-http-server"

puccini-tosca compile "http://localhost:8000/openstack.csar" "$@"
