#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

puccini-tosca compile "$ROOT/examples/tosca/requirements-and-capabilities.yaml" "$@" | \
puccini-clout scriptlet exec tosca.resolve
