#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

# -count=1 is the idiomatic way to disable test caching

echo 'testing...'

ROOT=$ROOT \
go test -count=1 "$MODULE/puccini-tosca" "$@"
