#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build-wrapper-java"

git_version

# Build
mvn --file "$ROOT/examples/java" --define puccini.version=${VERSION:1}

# Run
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROOT/dist \
mvn --quiet --file "$ROOT/examples/java" \
	exec:java --define exec.args="$ROOT/examples/1.3/inputs-and-outputs.yaml --input=ram=1gib --input=cores=6" --errors
