#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build-wrapper-ruby"

gem install "$ROOT/dist/puccini.gem"

"$ROOT/examples/ruby/compile.rb" "$ROOT/examples/1.3/inputs-and-outputs.yaml" --input=ram=1gib --input=cores=6 "$@"
