#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build-wrapper-python"

. "$ROOT/dist/python-env/bin/activate"
"$ROOT/examples/python/compile.py" "$ROOT/examples/tosca/data-types.yaml"
