#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build-csar"

puccini-tosca compile "$ROOT/dist/cloud.csar" "$@"
puccini-tosca compile "$ROOT/dist/cloud.csar" --template="other 1.yaml" "$@"
puccini-tosca compile "$ROOT/dist/cloud.csar" --template=2 "$@"
