#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

# Test sdist by default
FLAG=${1:--s}

SUFFIX=$SUFFIX "$HERE/build-wrapper-python" "$FLAG"
. "$ROOT/dist/python-env/bin/activate"

"$ROOT/examples/python/compile.py" "$ROOT/examples/1.3/inputs-and-outputs.yaml" --input=ram=1gib --input=cores=6
