#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

SUFFIX=$SUFFIX "$HERE/build-wrapper-ansible"
. "$ROOT/dist/python-env/bin/activate"

cd "$ROOT/examples/ansible/tasks"

ansible-playbook playbook.yaml
