#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

m 'test...'
"$HERE/test"
m 'build-library...'
"$HERE/build-library"
m 'build-csars...'
"$HERE/build-csars"

export NOBUILD=true

m 'test-parse...'
"$HERE/test-parse"

m 'test-formats...'
"$HERE/test-formats"

m 'test-csar...'
"$HERE/test-csar"

m 'test-https-url...'
"$HERE/test-https-url"
m 'test-git-url...'
"$HERE/test-git-url"
m 'test-csar-http-url...'
"$HERE/test-csar-http-url"
m 'test-archive-url...'
"$HERE/test-archive-url"
m 'test-archive-url-http...'
"$HERE/test-archive-url-http"

m 'test-wasm...'
"$HERE/test-wasm"
m 'test-wasip1...'
"$HERE/test-wasip1"
m 'test-java...'
"$HERE/test-java"
m 'test-python...'
"$HERE/test-python"
m 'test-ruby...'
"$HERE/test-ruby"

m done!
