#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

# -count=1 is the idiomatic way to disable test caching

m 'testing...'

ROOT=$ROOT \
go test -count=1 -timeout=10s "$MODULE/puccini-tosca" "$@"
