#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

puccini-tosca compile \
https://raw.githubusercontent.com/tliron/puccini/main/examples/tosca/data-types.yaml "$@"
