#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

m 'test...'
"$HERE/test"
m 'build-library...'
"$HERE/build-library"
m 'test-js...'
"$HERE/test-js"
m 'test-https...'
"$HERE/test-https"
m 'test-csar...'
"$HERE/test-csar"
m 'test-csar-http...'
"$HERE/test-csar-http"
m 'test-zip...'
"$HERE/test-zip"
m 'test-zip-http...'
"$HERE/test-zip-http"
m 'test-git...'
"$HERE/test-git"
m 'test-wasm...'
"$HERE/test-wasm"
m 'test-java...'
"$HERE/test-java"
m 'test-python...'
"$HERE/test-python"
m 'test-ruby...'
"$HERE/test-ruby"

m done!
